# config
cover: /img/road.jpg
logo: /img/bicycle.svg
top_saying:
- title: A good programmer is someone who always looks both ways before crossing a one-way street.
  content: Doug Linder
bottom_saying: 
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: UX/DESIGN
  works_url: /resume.md
- works_name: CRAFT
  works_url: /

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/hubuntub
twitter: https://twitter.com/hubuntub

#about  timeline
timeline:
- num: 1
  word: AGFA-HEALTHCARE
  period: FEVRIER - JUILLET 2011
  place: Bordeaux
- num: 2
  word: NEXTEP
  period: JANVIER - OCTOBRE 2012
  place: Bordeaux
- num: 3
  word: CM2D 
  period: NOVEMBRE 2012 - AVRIL 2014
  place: Bordeaux
- num: 4
  word: GENERAL ELECTRIC REAL ESTATE
  period: MAI 2014 - MAI 2015
  place: Paris, La Défense
- num: 5
  word: CRISTALLIN
  period: AVRIL 2015
  place: Troyes
- num: 6
  word: ARGUS DE LA PRESSE 
  period: JUIN 2015 - JUIN 2016
  place: Paris
- num: 7
  word: ING DIRECT / SCRUM MASTER 
  period: JUIN 2016 - PRÉSENT
  place: Paris

#Links
links:
- name: Kieran
  link: http://go.kieran.top/
- name: Name
  link: http://domain.com/